### ISSUE TITLE
Amazon Linux Support

### ISSUE THREAD

**Issue by michaelkrieg** [dev-sec/linux-patch-baseline#10]
Although Amazon Linux can be roughly treated as RHEL / CentOS family, this will not work here, because inspec detects "amazon" instead of "redhat".

Adding another condition to libraries/linux_updates.rb does not work as a quick and dirty trick.

Can you advise please?

**Comment by Stromweld** [comment]
This was fixed by this line https://github.com/dev-sec/linux-patch-baseline/blob/master/libraries/linux_updates.rb#L31

**Comment by rndmh3ro** [comment]
Thanks for noticing @Stromweld!
