### ISSUE TITLE
HTML report generated for InSpec Profile contains error

### ISSUE THREAD

**Issue by amitchettri** [dev-sec/linux-patch-baseline#25]
HTML report generated using the inspec CLI flag **--reporter** for the inspec profile **linux-patch-baseline, linux-baseline** etc contains error message and need re-styling.

**Example: report generated using linux-patch-baseline inspec profile but similar error face with dev-sec/nginx-baseline, dev-sec/linux-patch-baseline**

_Though in the normal CLI output there is no error._

`inspec exec /home/admchef/inspec/linux-patch-baseline/ -t ssh://user:password@target --reporter html:ubuntu.html`

![image](https://user-images.githubusercontent.com/46727623/78950894-d35ac300-7aed-11ea-9c53-e47664423a14.png)

**Comment by amitchettri** [comment]
To add more **System Package bsdutils** is a failed as the package version "**expected and got**" is different for this package and all the other package as well, but still this appears under passed. 

So if anyone unchecked passed checkbox, then **System Package bsdutils** and other package's in the report gets removed and only version is available thus making hard to understand about which package this failed is.

checking the HTML code it show that **System Package bsdutils** have the **class=example_group passed and class=passed** rather than having **class=example_group failed and class=failed**
![image](https://user-images.githubusercontent.com/46727623/78951961-92fd4400-7af1-11ea-92e6-e80e5a7ad044.png)

**Comment by chris-rock** [comment]
@amitchettri Thank you for the report. There is nothing we can do about the reporter since that is core to InSpec. The DevSec team only maintains the InSpec tests. I saw that you already opened an issue with InSpec https://github.com/inspec/inspec/issues/4972, therefore I am going to close this issue here. Please reopen if you think this is an issue with the profile itself.

**Comment by amitchettri** [comment]
Hello @chris-rock,

Thank you for your response and Yes i agree with you as i have notice same error with other profiles as well so this can't be profile related issue. But I am hoping is there a possibility that you or someone can help with inspec/inspec#4972?
