### ISSUE TITLE
Version 8 Does not work with baseline

### ISSUE THREAD

**Issue by amitchettri** [dev-sec/linux-patch-baseline#47]
Hello Dev_Sec Team,

can i know by when the support for the RHEL/CentOS 8 will  be available ?

Regards
Amit

**Comment by jdwge** [comment]
Seconding @amitchettri's request. I'm building images and containers in Azure and AWS the Red Hat 8 support would be a boon to my organization as well.

**Comment by rndmh3ro** [comment]
If any of you would like to help - we'd love some PRs!

**Comment by amitchettri** [comment]
@rndmh3ro,

I was able to code a python script to get the required details in rhel 8. But I wonder how I fit the same code in linux_update.rb file.
Yet not very expert on this.

**Comment by rndmh3ro** [comment]
Well, we need ruby code. :)
Can you share the python code? then we can take a look how to translate it into ruby.

**Comment by aaronlippold** [comment]
The current resource use python calls in the ruby code ... you should be
able to support 8 with a case statement and just updating the python calls
--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by amitchettri** [comment]
i will PR it. soon. i only need to do 1 round of testing with few 8 platforms

**Comment by amitchettri** [comment]
I have made the test but looks like some pre-check test failed for the PR, I am not sure what is that and may be someone with write access can fix this minor change and push.

As i tested in my ENV it works properly.
![image](https://user-images.githubusercontent.com/46727623/112756610-a86dc580-9003-11eb-8c0e-10da907ff330.png)

**Comment by schurzi** [comment]
solved by #57
